FROM python:3.10

# Set the working directory
WORKDIR /app
COPY ./proto_schema_registry/requirements.txt .
# Install dependencies
RUN pip install --no-cache-dir -r ./requirements.txt

# Copy the application files
COPY ./proto_schema_registry/src ./src

WORKDIR /app/src
# Expose the application port
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "protobuf_schema_registry:app", "--host", "0.0.0.0", "--port", "8000"]
