# kafka-cluster.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
spec:
  ports:
    - port: 9093
  selector:
    app: kafka-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-cluster
spec:
  serviceName: "kafka-cluster"
  replicas: 2
  selector:
    matchLabels:
      app: kafka-cluster
  template:
    metadata:
      labels:
        app: kafka-cluster
    spec:
      containers:
        - name: kafka-cluster
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 29092
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_BROKER_ID
              value: "$(BROKER_ID)"
            - name: KAFKA_CLUSTER_ID
              value: "hfQDOMyLSeGPxjBa7e__Fg"  # Replace with your expected cluster ID
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:29092,INTERNAL://0.0.0.0:9092,DNS://0.0.0.0:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(POD_IP):29092,INTERNAL://$(POD_IP):9092,DNS://$(POD_NAME):9093"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,DNS:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
          command: ["/bin/bash", "-c"]
          args:
            - export BROKER_ID=${POD_NAME##*-} &&
              export KAFKA_BROKER_ID=$BROKER_ID &&
              echo "Using kafka Broker id >>>>>>>.>>>>>>.>>>> $KAFKA_BROKER_ID and $POD_NAME" &&
              exec /etc/confluent/docker/run
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
