# Use a lightweight Python image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /schemas

# Copy all .proto schema files to the container
COPY schemas /schemas

# Expose the HTTP port
EXPOSE 8080

# Start the HTTP server when the container runs
CMD ["python3", "-m", "http.server", "8080", "--directory", "/schemas"]
