# Use a Python base image
FROM python:3.9-slim

# Set environment variables
ENV KAFKA_BROKER=localhost:9092


# Set working directory

# Install dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
WORKDIR /src
