# Use a Python base image
FROM python:3.9-slim

# Install dependencies
COPY avro_producer/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir confluent-kafka[avro]


WORKDIR /src
# Copy the application files
COPY avro_producer/src .
COPY shared/producers ./producers
# Command to run the script
CMD ["python", "-m", "avro_producer" ]
# CMD [ "bash" ]
