version: '3.8'

networks:
  kafka_network:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://${KAFKA_EXTERNAL_URL},PLAINTEXT_INTERNAL://${KAFKA_INTERNAL_URL}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_EXTERNAL_URL},PLAINTEXT_INTERNAL://${KAFKA_INTERNAL_URL}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 1
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server ${KAFKA_INTERNAL_URL} --list || exit 1"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s
    networks:
      - kafka_network

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://${KAFKA_INTERNAL_URL}
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://schema-registry:8081/subjects"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s
    networks:
      - kafka_network

  protobuf-registry:
    build:
      dockerfile: ./proto_schema_registry/docker/dockerfile.buff-server
      context: ./projects
    ports:
      - "8000:8000"
    volumes:
      - ./schemas:/schemas
    restart: always
    networks:
      - kafka_network
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_INTERNAL_URL}"
    env_file:
      - .env
  
  avro-producer:
    image: avro-producer
    build:
      dockerfile: avro_producer/docker/dockerfile.avro_producer
      context: ./projects
    environment:
      KAFKA_BROKERS: "${KAFKA_INTERNAL_URL}"
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
      TOPIC: bronze
    env_file:
      - .env
    depends_on:
      schema-registry:
        condition: service_healthy
    restart: always
    ports:
      - "4000:5000"
    networks:
      - kafka_network
